# Generated by Django 4.1.2 on 2023-01-08 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
        ('utils', '0003_alter_abstracid_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('abstracid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.abstracid')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فارسی')),
                ('title_eng', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان انگلیسی')),
                ('keyword', models.CharField(max_length=250, verbose_name='کلمه کلیدی')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('amount', models.IntegerField(verbose_name='تعداد')),
                ('status', models.CharField(choices=[('True', 'فعال'), ('False', 'غیرفعال')], default=False, max_length=50, verbose_name='وضعیت')),
                ('product_status', models.CharField(choices=[('New', 'نو'), ('Used-good', 'در حد نو'), ('Old', 'کهنه')], max_length=50, verbose_name='کیفیت کالا')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='عبارت لینک')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در تاریخ')),
                ('change', models.BooleanField(default=False, verbose_name='قابل معاوضه')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.brand', verbose_name='برند')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', verbose_name='دسته')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
            bases=('utils.abstracid', models.Model),
        ),
    ]
