# Generated by Django 4.1.5 on 2023-01-07 16:33

import category.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAbstractModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('baseabstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='category.baseabstractmodel')),
                ('name', models.CharField(max_length=50, verbose_name='نام برند')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'دسته\u200cبندی برند',
            },
            bases=('category.baseabstractmodel',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('baseabstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='category.baseabstractmodel')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('en_title', models.CharField(max_length=50, verbose_name='عنوان انگلیسی')),
                ('keyword', models.CharField(max_length=250, verbose_name='کلمه کلیدی')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('True', 'فعال'), ('False', 'غیرفعال')], max_length=50, verbose_name='وضعیت')),
                ('image', models.ImageField(blank=True, upload_to=category.models.upload_image_path, verbose_name='تصویر')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='عبارت لینک')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاده شده در تاریخ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در تاریخ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='category.category', verbose_name='دسته\u200cمادر')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته\u200cبندی\u200c',
            },
            bases=('category.baseabstractmodel',),
        ),
    ]
