# Generated by Django 4.1.2 on 2023-01-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.UUIDField(default='c254851b74ee45aa966102e1cf2f9f75', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ایدی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default='c254851b74ee45aa966102e1cf2f9f75', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ایدی'),
        ),
    ]
