# Generated by Django 4.1.2 on 2023-01-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='product',
        ),
    ]
