# Generated by Django 4.1.2 on 2023-01-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('blog', '0002_remove_blog_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='product.product'),
            preserve_default=False,
        ),
    ]
