# Generated by Django 4.1.2 on 2022-12-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='car_insurance_file',
        ),
        migrations.RemoveField(
            model_name='user',
            name='car_technical_inspection_file',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driver_rate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driving_license_file',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
