# Generated by Django 4.1.5 on 2023-01-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='Attribute_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attributegroup', verbose_name='attribute'),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_group', to='category.category'),
        ),
    ]
