# Generated by Django 4.1.2 on 2023-01-10 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0004_alter_productattribute_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='Attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attributeitem'),
        ),
    ]
