# Generated by Django 4.1.2 on 2023-01-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_alter_productattribute_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='Attribute',
            new_name='AttributeItem',
        ),
    ]
