# Generated by Django 4.1.5 on 2023-01-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configure',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AlterField(
            model_name='configure',
            name='fav_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac_icon', to='utils.images', verbose_name='فاو آیکون'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='nav_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='van_icon', to='utils.images', verbose_name='ناو آیکون'),
        ),
    ]
