# Generated by Django 4.1.2 on 2023-01-07 17:47

from django.db import migrations, models
import django.db.models.deletion
import utils.api.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstracId',
            fields=[
                ('id', models.CharField(default='4c8c6a2716664e06a664a1b20b8ffb35', max_length=30, primary_key=True, serialize=False, verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('abstracid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.abstracid')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, upload_to=utils.api.utils.upload_image_path, verbose_name='تصویر')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
            bases=('utils.abstracid', models.Model),
        ),
    ]
