# Generated by Django 4.1.2 on 2023-01-08 08:08

from django.db import migrations, models
import django.db.models.deletion
import utils.api.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstracId',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ایدی')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('abstracid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.abstracid')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, upload_to=utils.api.utils.upload_image_path, verbose_name='تصویر')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
            bases=('utils.abstracid', models.Model),
        ),
    ]
