# Generated by Django 4.1.2 on 2023-01-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstracid',
            name='id',
            field=models.CharField(default='d833ecdf8fea4e81b1e19d67bde2eb31', max_length=40, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
