# Generated by Django 4.1.2 on 2023-01-08 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='create_at',
        ),
        migrations.AddField(
            model_name='abstracid',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 8, 13, 44, 836133, tzinfo=datetime.timezone.utc), verbose_name='زمان ایجاد'),
        ),
    ]
