# Generated by Django 4.1.2 on 2023-01-08 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_remove_images_create_at_abstracid_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstracid',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
        ),
    ]
