# Generated by Django 4.1.2 on 2023-01-08 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_images_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ایدی'),
        ),
    ]
